// Public surface of react-native-gtkx, mirroring the `react-native` module.
// Components · APIs · StyleSheet, with the Yoga layout engine underneath.

export {
  ActivityIndicator,
  Animated,
  AppRegistry,
  Circle,
  Defs,
  Easing,
  Ellipse,
  FlatList,
  G,
  Image,
  Line,
  LinearGradient,
  Modal,
  IntrinsicRoot,
  NestedRoot,
  Path,
  Polygon,
  Polyline,
  Pressable,
  RadialGradient,
  Rect,
  Root,
  SafeAreaView,
  ScrollView,
  SectionList,
  StatusBar,
  Stop,
  Svg,
  Switch,
  Text,
  TextInput,
  TouchableOpacity,
  View,
  type ActivityIndicatorProps,
  type AnimatableNumber,
  type CircleProps,
  type DefsProps,
  type EllipseProps,
  type FlatListProps,
  type GProps,
  type ImageProps,
  type ImageSource,
  type LayoutEvent,
  type LinearGradientProps,
  type LineProps,
  type ListRenderItemInfo,
  type ModalProps,
  type PathProps,
  type PolygonProps,
  type PolylineProps,
  type PressableProps,
  type PressableStateCallbackType,
  type IntrinsicRootProps,
  type NestedRootProps,
  type PressEvent,
  type RadialGradientProps,
  type RectProps,
  type RootProps,
  type RunApplicationParams,
  type ScrollEvent,
  type ScrollViewHandle,
  type ScrollViewProps,
  type SectionListProps,
  type StopProps,
  type SvgFillRule,
  type SvgLineCap,
  type SvgLineJoin,
  type SvgProps,
  type SwitchProps,
  type TextInputProps,
  type TextProps,
  type TouchableOpacityProps,
  type ViewabilityConfig,
  type ViewProps,
  type ViewToken,
} from "./components/index"

// List scroll handle (scrollTo/scrollToEnd/scrollToIndex/scrollToItem/
// scrollToOffset) — exported straight from the component module.
export type { FlatListHandle } from "./components/flat-list"

export {
  Alert,
  Appearance,
  AppState,
  BackHandler,
  DevSettings,
  Dimensions,
  I18nManager,
  InteractionManager,
  Linking,
  Platform,
  useColorScheme,
  useWindowDimensions,
  type AlertButton,
  type AlertButtonStyle,
  type AlertOptions,
  type AppearancePreferences,
  type AppStateEvent,
  type AppStateStatus,
  type ColorSchemeName,
  type DimensionKey,
  type DimensionsPayload,
  type InteractionPromise,
  type PlatformSelectSpec,
  type ScaledSize,
} from "./apis/index"

export { PlatformColor, StyleSheet } from "./style/index"

export type {
  DimensionValue,
  FlatStyle,
  LayoutStyle,
  PointerEventsValue,
  StyleProp,
  TransformPart,
  VisualStyle,
} from "./contracts"

export const version = "0.1.0"
