// GENERATED FILE — do not edit by hand.
// Produced by scripts/generate-widget-surface.ts. Re-run it inside the VM
// after `npm run codegen` picks up a gtkx update; see
// scripts/widget-surface/classification.json for the full classification
// and .claude/epics/widget-surface/ for the rules behind it.
//
// Every widget the classifier resolved to a Gtk.Widget subclass, re-exported
// RAW. This is the only generated file (besides the hand-written bridge
// modules) allowed to import @gtkx/jsx directly — src/gtk/widgets.generated
// pulls from here instead, so the no-restricted-imports carve-out for
// src/gtkx/bridge/** stays the only door. Adwaita's raw widgets are the
// sibling file, widgets.generated.adw.ts — see gtkx/bridge/adw.ts.

export {
  GtkAboutDialog,
  GtkActionBar,
  GtkAppChooserButton,
  GtkAppChooserDialog,
  GtkAppChooserWidget,
  GtkApplicationWindow,
  GtkAspectFrame,
  GtkAssistant,
  GtkBox,
  GtkButton,
  GtkCalendar,
  GtkCellView,
  GtkCenterBox,
  GtkCheckButton,
  GtkColorButton,
  GtkColorChooserDialog,
  GtkColorChooserWidget,
  GtkColorDialogButton,
  GtkColumnView,
  GtkComboBox,
  GtkComboBoxText,
  GtkDialog,
  GtkDragIcon,
  GtkDrawingArea,
  GtkDropDown,
  GtkEditableLabel,
  GtkEmojiChooser,
  GtkEntry,
  GtkExpander,
  GtkFileChooserDialog,
  GtkFileChooserWidget,
  GtkFixed,
  GtkFlowBox,
  GtkFlowBoxChild,
  GtkFontButton,
  GtkFontChooserDialog,
  GtkFontChooserWidget,
  GtkFontDialogButton,
  GtkFrame,
  GtkGLArea,
  GtkGraphicsOffload,
  GtkGrid,
  GtkGridView,
  GtkHeaderBar,
  GtkIconView,
  GtkImage,
  GtkInfoBar,
  GtkInscription,
  GtkLabel,
  GtkLevelBar,
  GtkLinkButton,
  GtkListBox,
  GtkListBoxRow,
  GtkListView,
  GtkLockButton,
  GtkMediaControls,
  GtkMenuButton,
  GtkMessageDialog,
  GtkNotebook,
  GtkOverlay,
  GtkPageSetupUnixDialog,
  GtkPaned,
  GtkPasswordEntry,
  GtkPicture,
  GtkPopover,
  GtkPopoverBin,
  GtkPopoverMenu,
  GtkPopoverMenuBar,
  GtkPrintUnixDialog,
  GtkProgressBar,
  GtkRange,
  GtkRevealer,
  GtkScale,
  GtkScaleButton,
  GtkScrollbar,
  GtkScrolledWindow,
  GtkSearchBar,
  GtkSearchEntry,
  GtkSeparator,
  GtkShortcutLabel,
  GtkShortcutsGroup,
  GtkShortcutsSection,
  GtkShortcutsShortcut,
  GtkShortcutsWindow,
  GtkSpinButton,
  GtkSpinner,
  GtkStack,
  GtkStackSidebar,
  GtkStackSwitcher,
  GtkStatusbar,
  GtkSwitch,
  GtkText,
  GtkTextView,
  GtkToggleButton,
  GtkTreeExpander,
  GtkTreeView,
  GtkVideo,
  GtkViewport,
  GtkVolumeButton,
  GtkWindow,
  GtkWindowControls,
  GtkWindowHandle,
} from "@gtkx/jsx/gtk"
